export default [
  'babel-polyfill',
  'whatwg-fetch',
  'core-js',
  'humps',
  'immutable',
  'react',
  'react-dom',
  'react-js-pagination',
  'react-on-rails',
  'react-redux',
  'react-select',
  'redux',
  'redux-immutable',
];
