export default [
  'core-js',
  'humps',
  'immutable',
  'number-abbreviate',
  'react',
  'react-bootstrap',
  'react-dom',
  'react-js-pagination',
  'react-on-rails',
  'react-redux',
  'react-select',
  'redux',
  'redux-form',
  'redux-immutable',
  'redux-thunk',
  'render-if',
];
